import {StyleSheet} from 'react-native';

export const accountProfileStyles = StyleSheet.create({
  container: {
    padding: 18,
    flexGrow: 1,
  },
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  headerCard: {
    alignItems: 'center',
    marginBottom: 18,
    paddingBottom: 4,
    borderBottomColor: '#eaeaea',
    borderBottomWidth: 1,
  },
  profileName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 2,
  },
  profileEmail: {
    fontSize: 13,
    color: '#888',
    marginBottom: 2,
  },
  infoCard: {
    backgroundColor: '#f6f7fb',
    borderRadius: 12,
    padding: 16,
    marginBottom: 18,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 2,
    shadowOffset: {width: 0, height: 2},
  },
  infoRow: {
    fontSize: 15,
    color: '#1a237e',
    marginBottom: 5,
  },
  infoLabel: {
    fontWeight: '600',
    color: '#495057',
  },
  rolesCard: {
    backgroundColor: '#f3fafc',
    borderRadius: 12,
    padding: 14,
    marginBottom: 32,
    elevation: 1,
  },
  rolesTitle: {
    fontWeight: 'bold',
    color: '#166534',
    fontSize: 16,
    marginBottom: 6,
    letterSpacing: 0.1,
  },
  roleItem: {
    marginBottom: 10,
    backgroundColor: '#fff',
    borderRadius: 7,
    padding: 8,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    shadowOffset: {width: 0, height: 1},
  },
  roleName: {marginLeft: 7, color: '#1E90FF', fontWeight: 'bold', fontSize: 15},
  roleSite: {marginLeft: 8, color: '#606060', fontSize: 13, fontWeight: '600'},
  rolePerm: {marginLeft: 24, fontSize: 13, color: '#555', marginTop: -3},
  logoutBtn: {
    flexDirection: 'row',
    backgroundColor: '#e74c3c',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    shadowColor: '#e74c3c',
    shadowOpacity: 0.14,
    shadowRadius: 2,
    elevation: 1,
  },
});
