import {StyleSheet} from 'react-native';

export const agendaFormStyles = StyleSheet.create({
  container: {flex: 1},
  safeArea: {flex: 1},
  scrollContainer: {padding: 16, paddingBottom: 40},
  card: {
    backgroundColor: 'white',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  title: {
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 18,
    color: '#2463EB',
    textAlign: 'center',
    marginVertical: 18,
  },
  cardHeader: {
    backgroundColor: '#ffffffff',
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {color: '#2463EB', fontWeight: '700', fontSize: 16},
  cardIcon: {color: 'white', fontSize: 18},
  cardContent: {padding: 14},
  label: {fontWeight: '600', marginBottom: 6, marginTop: 8},
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#f9f9f9',
  },
  textArea: {height: 80, textAlignVertical: 'top'},
  dateInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#f9f9f9',
  },
  button: {
    backgroundColor: '#2463EB',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 12,
  },
  detailText: {
    fontSize: 14,
    marginBottom: 4,
  },
  detailLabel: {
    fontWeight: '700',
  },
  buttonText: {color: 'white', fontWeight: '700', fontSize: 16},
  inputIOS: {
    fontSize: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    color: 'black',
    paddingRight: 30,
  },
  inputAndroid: {
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    color: 'black',
    paddingRight: 30,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 16, // Jika React Native >= 0.71
  },
  inputContainer: {
    flex: 1,
    marginVertical: 5,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  disabledInput: {
    backgroundColor: '#f1f5f9',
    color: '#888',
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    width: '100%',
    height: '100%',
  },
});
