import {StyleSheet} from 'react-native';

export const createP2HStyles = StyleSheet.create({
  container: {flex: 1, paddingHorizontal: 12},
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  refreshButton: {
    backgroundColor: '#007bff',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  refreshButtonText: {
    color: 'white',
    fontWeight: '600',
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 6,
    borderRadius: 12,
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  statusText: {
    fontWeight: '600',
  },
  title: {
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 18,
    color: '#2463EB',
    textAlign: 'center',
    marginVertical: 18,
  },
  label: {fontWeight: 'bold', fontSize: 13, color: '#333', marginTop: 12},
  input: {
    borderWidth: 1,
    borderColor: '#e3e8f0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    backgroundColor: '#fff',
    marginTop: 4,
    marginBottom: 2,
  },
  button: {
    marginTop: 22,
    backgroundColor: '#2463EB',
    borderRadius: 10,
    alignItems: 'center',
    paddingVertical: 14,
    marginHorizontal: 24,
    marginBottom: 26,
    elevation: 2,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
    letterSpacing: 1,
  },
  buttonDisabled: {backgroundColor: '#aac4f7'},
  card: {
    backgroundColor: '#fff',
    borderRadius: 13,
    padding: 14,
    marginVertical: 10,
    elevation: 2,
    shadowColor: '#2463EB',
    shadowOpacity: 0.07,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
  },
  cardTitle: {
    fontWeight: '700',
    color: '#2463EB',
    fontSize: 16,
    marginBottom: 8,
  },
  checklistCard: {marginBottom: 14},
  radioRow: {flexDirection: 'row', flexWrap: 'wrap', marginTop: 4},
  radioTouchable: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 14,
    marginBottom: 5,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#2463EB',
    marginRight: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  radioOuterActive: {backgroundColor: '#2463EB', borderColor: '#2463EB'},
  radioInnerFullBlue: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#2463EB',
  },
  radioLabel: {fontSize: 13, color: '#444'},
  radioLabelActive: {color: '#2463EB', fontWeight: 'bold'},
  radioButton2: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#2463EB',
    marginRight: 8,
  },
  radioButton2Active: {backgroundColor: '#2463EB'},
  radioText2: {color: '#2463EB', fontWeight: '700'},
  radioText2Active: {color: '#fff'},
});
