import {StyleSheet, Dimensions} from 'react-native';
const {width: SCREEN_WIDTH} = Dimensions.get('window');
export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff', // Sesuai gambar, putih
    paddingTop: 22,
    paddingHorizontal: 18,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 4,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#444A5A',
    marginBottom: 2,
    letterSpacing: 0.2,
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 30,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarIcon: {
    fontSize: 40,
    color: '#222',
  },
  welcome: {
    fontWeight: 'bold',
    fontSize: 18,
    color: '#222',
    marginTop: 2,
    marginBottom: 1,
  },
  notif: {
    fontSize: 14,
    color: '#757686',
    marginBottom: 8,
    fontWeight: '400',
  },
  logoutBtn: {
    position: 'absolute',
    right: 0,
    top: 2,
    padding: 8,
    backgroundColor: '#fbeaea',
    borderRadius: 15,
    zIndex: 10,
  },
  carouselContainer: {
    marginTop: 18,
    marginBottom: 12,
    minHeight: 155, // cukup 3 baris
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselCard: {
    backgroundColor: '#6E97CA',
    borderRadius: 20,
    width: SCREEN_WIDTH * 0.8, // 80% dari layar
    minHeight: 115,
    maxHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginHorizontal: (SCREEN_WIDTH * 0.1) / 2,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#222',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  carouselText: {
    color: '#fff',
    fontSize: 15,
    textAlign: 'center',
    fontWeight: '400',
    lineHeight: 22,
    width: '50%',
    flexShrink: 1,
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 7,
    marginBottom: 3,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#222',
    marginHorizontal: 4,
    opacity: 0.26,
  },
  dotActive: {
    opacity: 1,
    backgroundColor: '#222',
  },
  menuModuleContainer: {
    marginTop: 18,
    marginBottom: 8,
    paddingHorizontal: 12,
  },
  sectionTitle: {
    fontWeight: '700',
    fontSize: 16,
    color: '#29436e',
    marginBottom: 8,
    marginLeft: 3,
  },
  menuModuleGrid: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 14,
  },
  menuModuleCard: {
    backgroundColor: '#fff',
    borderRadius: 17,
    paddingVertical: 22,
    paddingHorizontal: 16,
    margin: 7,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    minWidth: 140,
    maxWidth: '47%',
    elevation: 2,
    shadowColor: '#1E90FF',
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  menuModuleText: {
    color: '#29436e',
    fontWeight: '600',
    fontSize: 15,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.08)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  dropdownMenu: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginTop: 58, // supaya muncul tepat di bawah titik tiga
    marginRight: 18,
    paddingVertical: 7,
    paddingHorizontal: 14,
    elevation: 6,
    minWidth: 130,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 6,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 2,
  },
  dropdownText: {
    marginLeft: 12,
    fontSize: 15,
    color: '#222',
  }, // Tambahkan di bawah style yang lain di dashboardStyles
  siteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 3,
    marginTop: 5,
  },
  siteLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1E90FF',
    marginRight: 7,
  },
  siteChip: {
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 15,
    backgroundColor: '#f2f6fa',
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e1e7ee',
  },
  siteChipText: {
    fontSize: 14,
    color: '#4b6178',
  },
  siteChipActive: {
    backgroundColor: '#e8f5ff',
    borderColor: '#3498db',
  },
  siteChipTextActive: {
    color: '#3498db',
    fontWeight: 'bold',
  },
  moduleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 0,
  },
  moduleName: {
    fontWeight: '600',
    fontSize: 15,
    color: '#29436e',
    marginRight: 8,
    minWidth: 64,
  },
  modulePermit: {
    color: '#1E90FF',
    fontSize: 13,
    marginRight: 8,
    fontWeight: 'bold',
  },
  moduleRoleName: {
    color: '#757686',
    fontSize: 13,
    fontStyle: 'italic',
  },
});
