import {StyleSheet, Platform, Dimensions} from 'react-native';

const {width: SCREEN_WIDTH} = Dimensions.get('window');

export const dashboardStyles = StyleSheet.create({
  // ================= Container & Header =================
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? 8 : 0,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 4,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#444A5A',
    marginBottom: 2,
    letterSpacing: 0.2,
    marginVertical: 18,
  },
  greeting: {fontSize: 20, fontWeight: 'bold', color: '#183153'},
  subGreeting: {fontSize: 14, color: '#555'},
  headerMenu: {padding: 8},
  logoutBtn: {
    position: 'absolute',
    right: 0,
    top: 2,
    padding: 8,
    backgroundColor: '#fbeaea',
    borderRadius: 15,
    zIndex: 10,
  },

  // ================= Carousel =================
  carouselContainer: {
    marginTop: 18,
    marginBottom: 12,
    minHeight: 155,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselCard: {
    backgroundColor: '#2463EB',
    borderRadius: 20,
    width: SCREEN_WIDTH * 0.8,
    minHeight: 115,
    maxHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginHorizontal: (SCREEN_WIDTH * 0.1) / 2,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#222',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  carouselText: {
    color: '#fff',
    fontSize: 15,
    textAlign: 'center',
    fontWeight: '400',
    lineHeight: 22,
    width: '50%',
    flexShrink: 1,
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 7,
    marginBottom: 3,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#222',
    marginHorizontal: 4,
    opacity: 0.26,
  },
  dotActive: {
    opacity: 1,
    backgroundColor: '#222',
  },

  // ================= Profile Card =================
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  profileAvatar: {
    marginRight: 14,
    backgroundColor: '#f0f0f0',
    borderRadius: 40,
    padding: 6,
  },
  profileName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 2,
  },
  profileInfo: {flex: 1},
  profileInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    gap: 8,
  },
  profileId: {fontSize: 13, color: '#6b7280', marginBottom: 1, marginRight: 10},
  profileDept: {
    fontSize: 13,
    color: '#3080d0',
    fontWeight: '600',
    marginBottom: 1,
    marginRight: 10,
  },
  profilePosition: {
    fontSize: 13,
    color: '#2d9d78',
    fontWeight: '600',
    marginBottom: 1,
  },

  // ================= Site Selector =================
  siteListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    marginTop: 6,
  },
  siteListLabel: {
    fontSize: 14,
    color: '#555',
    fontWeight: '600',
    marginRight: 10,
  },
  siteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 4,
  },
  siteLabel: {
    fontSize: 13,
    fontWeight: '600',
    marginRight: 6,
    color: '#2463EB',
  },
  siteChip: {
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#e1e7ee',
  },
  siteChipActive: {backgroundColor: '#2463EB', borderColor: '#2463EB'},
  siteChipText: {fontSize: 12, color: '#2463EB'},
  siteChipTextActive: {color: '#fff', fontWeight: '600'},
  siteWarning: {color: 'red', fontSize: 13, fontWeight: 'bold'},

  // ================= Notifications / Absensi =================
  notifCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  notifIcon: {marginRight: 12},
  notifContent: {flex: 1},
  notifTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#164160',
    marginBottom: 4,
  },
  notifTime: {fontSize: 14, color: '#4caf50', marginBottom: 2},
  notifStatus: {fontSize: 13, color: '#444', textAlign: 'center', marginTop: 4},

  absenCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  absenRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  absenCol: {flex: 1, alignItems: 'center'},
  absenLabel: {fontSize: 12, color: '#555', marginTop: 4},
  absenValue: {fontSize: 16, fontWeight: 'bold', marginTop: 2},

  // ================= Quick Actions =================
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginVertical: 16,
  },
  quickAction: {
    width: '48%',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  quickActionLabel: {
    marginTop: 6,
    fontSize: 14,
    color: '#183153',
    fontWeight: '500',
  },

  // ================= Stats =================
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: '#fff',
    marginHorizontal: 4,
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  statValue: {fontSize: 16, fontWeight: 'bold', color: '#2463EB'},
  statLabel: {fontSize: 12, color: '#555', marginTop: 4},

  // ================= Modal & Dropdown =================
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  dropdownMenu: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginTop: 58,
    marginRight: 18,
    paddingVertical: 8,
    width: 220,
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 6,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  dropdownText: {marginLeft: 12, fontSize: 15, color: '#222'},
});
