import {StyleSheet, Dimensions} from 'react-native';
const {width: SCREEN_WIDTH} = Dimensions.get('window');

export const p2hDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    alignItems: 'center',
    padding: 16,
    marginTop: 10,
    marginBottom: 14,
    marginHorizontal: 10,
    elevation: 2,
    shadowColor: '#aaa',
    shadowOpacity: 0.08,
    shadowRadius: 5,
  },
  unitText: {
    fontSize: 21,
    fontWeight: 'bold',
    color: '#325AE7',
    marginBottom: 2,
    letterSpacing: 0.1,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 2,
  },
  driverText: {
    fontSize: 14,
    color: '#444',
    marginLeft: 8,
  },
  tglText: {
    fontSize: 14,
    color: '#444',
    marginLeft: 7,
  },
  sectionTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#1E293B',
    marginLeft: 13,
    marginBottom: 8,
  },
  errorText: {
    color: '#e74c3c',
    textAlign: 'center',
    marginTop: 16,
    fontSize: 15,
    fontWeight: '600',
  },
  emptyText: {
    color: '#888',
    fontSize: 15,
    textAlign: 'center',
    marginTop: 18,
    fontStyle: 'italic',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 13,
    marginBottom: 13,
    paddingVertical: 13,
    paddingHorizontal: 15,
    elevation: 1,
    shadowColor: '#dbeafe',
    shadowOpacity: 0.03,
    shadowRadius: 3,
  },
  noCircle: {
    width: 26,
    height: 26,
    borderRadius: 15,
    backgroundColor: '#e0ecff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 7,
    marginTop: 3,
  },
  noText: {
    fontWeight: '700',
    color: '#2463EB',
    fontSize: 15,
  },
  question: {
    color: '#222',
    fontWeight: '600',
    fontSize: 14,
    marginBottom: 4,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingHorizontal: 11,
    paddingVertical: 4,
    marginTop: 4,
    borderWidth: 1.1,
    borderColor: '#e0e7ef',
  },
  badgeText: {
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 0.15,
  },
});
