import {StyleSheet} from 'react-native';

export const p2hHistoryStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: 14,
    borderBottomColor: '#cbd6ee',
    marginBottom: 5,
  },
  title: {
    fontWeight: 'bold',
    fontSize: 18,
    color: '#1E90FF',
    marginBottom: 0,
  },
  list: {
    paddingHorizontal: 12,
    paddingBottom: 24,
    paddingTop: 2,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 15,
    marginBottom: 13,
    padding: 14,
    elevation: 2,
    shadowColor: '#aaa',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#e3eafe',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
  },
  unitText: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#1E90FF',
  },
  siteLabel: {
    backgroundColor: '#e3eafe',
    color: '#2563eb',
    fontSize: 13,
    fontWeight: 'bold',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  modelText: {
    color: '#444',
    fontWeight: '500',
    marginBottom: 3,
    fontSize: 14,
    marginTop: 1,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 1,
  },
  driverName: {
    color: '#3556aa',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 5,
  },
  rowSpace: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
    marginTop: 2,
  },
  labelInfo: {
    color: '#555',
    fontSize: 13,
    fontWeight: '500',
  },
  hmkm: {
    color: '#777',
    fontSize: 13,
    fontWeight: 'bold',
  },
  badgeRow: {
    flexDirection: 'row',
    marginTop: 4,
    marginBottom: 1,
  },
  badge: {
    borderWidth: 1.5,
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginRight: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    fontWeight: '600',
    fontSize: 13,
  },
  keteranganRow: {
    flexDirection: 'row',
    marginTop: 3,
  },
  ketLabel: {
    color: '#444',
    fontWeight: 'bold',
    fontSize: 13,
  },
  ketValue: {
    color: '#e67e22',
    fontWeight: '600',
    fontSize: 13,
    marginLeft: 2,
  },
  emptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 52,
    marginBottom: 52,
    paddingHorizontal: 26,
  },
  emptyText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
    textAlign: 'center',
    marginBottom: 2,
  },
  emptySubText: {
    color: '#fff',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 0,
  },
});
