export const tabelStyles = {
  pageTitle: {
    fontSize: 21,
    fontWeight: 'bold',
    color: '#1E90FF',
    marginBottom: 16,
    alignSelf: 'center',
  },
  searchInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 11,
    marginBottom: 14,
    fontSize: 15,
    borderColor: '#e6e8ec',
    borderWidth: 1,
  },
  pickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginLeft: 4,
  },
  pickerLabel: {
    fontWeight: '600',
    color: '#1E90FF',
    marginRight: 8,
    fontSize: 15,
  },
  pickerWrapper: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 4,
    borderColor: '#e6e8ec',
    borderWidth: 1,
    minWidth: 65,
  },
  picker: {
    color: '#1E90FF',
    fontSize: 15,
    paddingVertical: 5,
    textAlign: 'center',
  },
  cardExpanded: {
    backgroundColor: '#f1f8ff',
    borderColor: '#1E90FF',
    borderWidth: 1,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 10,
  },
  pageButton: {
    backgroundColor: '#1E90FF',
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 12,
    marginHorizontal: 8,
  },
  pageButtonDisabled: {
    backgroundColor: '#b0c4de',
  },
  pageButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  pageInfo: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1E90FF',
    marginHorizontal: 10,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardSectionTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#1E90FF',
    marginTop: 2,
    marginBottom: 2,
    letterSpacing: 0.2,
  },
  cardContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginBottom: 14,
    elevation: 3,
    shadowColor: '#1E90FF',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 3},
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
    borderBottomWidth: 1,
    borderColor: '#f2f2f2',
  },
  cardTitle: {
    fontWeight: 'bold',
    fontSize: 17,
    color: '#222',
  },
  cardSubtitle: {
    fontSize: 13,
    color: '#666',
    marginTop: 1,
  },
  cardSite: {
    color: '#1E90FF',
    fontWeight: 'bold',
    fontSize: 13,
    marginBottom: 2,
    textAlign: 'right',
  },
  cardDetail: {
    paddingHorizontal: 18,
    paddingVertical: 13,
    backgroundColor: '#f8fafc',
    borderTopWidth: 1,
    borderColor: '#f2f2f2',
  },
  cardDetailText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 4,
  },
  cardActionRow: {
    flexDirection: 'row',
    marginTop: 12,
    justifyContent: 'flex-end',
  },
  editButton: {
    backgroundColor: '#1976d2',
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 8,
    marginRight: 9,
  },
  deleteButton: {
    backgroundColor: '#E74C3C',
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 8,
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  // Extra (optional)
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 20,
    backgroundColor: '#1E90FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 13,
  },
};
